install-nvim:
	mkdir -p ~/.config/nvim 
	mkdir -p ~/.local/share/nvim/site/autoload
	sh -c 'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	ln -s ${pwd}/nvim  ~/.config/nvim
